# Generated by Django 5.0.4 on 2024-04-11 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_delivery', '0002_alter_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmd',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deilvery',
            name='status',
            field=models.BinaryField(default=0),
        ),
        migrations.CreateModel(
            name='CMD_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_delivery.cmd')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_delivery.items')),
            ],
        ),
    ]
