# Generated by Django 5.0.4 on 2024-04-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_delivery', '0004_alter_cmd_client_alter_cmd_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deilvery',
            new_name='Delivery',
        ),
    ]
