# Generated by Django 5.0.4 on 2024-04-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_delivery', '0005_rename_deilvery_delivery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery',
            new_name='Driver',
        ),
    ]
